# Generated by Django 4.1.7 on 2023-02-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='total',
            new_name='total_price',
        ),
    ]
